//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlueYonder.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trip
    {
        public Trip()
        {
            this.Reservations = new HashSet<Reservation>();
            this.Reservations1 = new HashSet<Reservation>();
        }
    
        public int TripId { get; set; }
        public int FlightScheduleID { get; set; }
        public int Status { get; set; }
        public int Class { get; set; }
        public string ThumbnailImage { get; set; }
    
        public virtual FlightSchedule FlightSchedule { get; set; }
        public virtual ICollection<Reservation> Reservations { get; set; }
        public virtual ICollection<Reservation> Reservations1 { get; set; }
    }
}
