//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlueYonder.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Location
    {
        public Location()
        {
            this.Flights = new HashSet<Flight>();
            this.Flights1 = new HashSet<Flight>();
        }
    
        public int LocationId { get; set; }
        public string Country { get; set; }
        public string State { get; set; }
        public string City { get; set; }
        public string CountryCode { get; set; }
        public string ThumbnailImageFile { get; set; }
        public string TimeZoneId { get; set; }
    
        public virtual ICollection<Flight> Flights { get; set; }
        public virtual ICollection<Flight> Flights1 { get; set; }
    }
}
